[tool.pytest.ini_options]
minversion = "7.0"

testpaths = ["tests"]
pythonpath = ["."]

[tool.coverage.run]
branch = true
source = ["backtester"]
omit = [
    "tests/*"
]

[tool.coverage.report]
show_missing = true
skip_covered = true
fail_under = 80


