[tool.pytest.ini_options]
minversion = "7.0"

testpaths = ["tests"]
pythonpath = ["."]

[tool.coverage.run]
branch = true
source = ["backtester"]
omit = [
    "tests/*",
    "backtester/price_loader.py",
]

[tool.coverage.report]
show_missing = true
skip_covered = false
fail_under = 90


